---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climatewavers-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climatewavers-mariadb
  template:
    metadata:
      labels:
        app: climatewavers-mariadb
    spec:
      containers:
        - env:
            - name: MARIADB_ROOT_PASSWORD
              value: waverx
          image: mariadb
          name: climatewavers-mariadb
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadbvolume
      volumes:
        - name: mariadbvolume
          persistentVolumeClaim:
            claimName: mariadbvolume